### ISSUE TITLE
降低 .NET Framework 依赖版本

### ISSUE THREAD

**Issue by mzji** [LeagueTavern/fix-lcu-window#4]
https://github.com/LeagueTavern/fix-lcu-window/blob/ae711ca81f0f97e1f5ba45a88972e47cc044843d/App.config#L4
https://github.com/LeagueTavern/fix-lcu-window/blob/ae711ca81f0f97e1f5ba45a88972e47cc044843d/Fix-LCU-Window.csproj#L11
建议降为 4.5 方便更多机器使用

**Comment by Coooookies** [comment]
感觉没有降的必要？（至少目前没有反馈有兼容性问题的）

**Comment by mzji** [comment]
主要是 Win 7 / 8 常见 4.5 ~ 4.5.2 ，而且目前用到的这些接口没有看到高版本 .NET framework 的需求，按照就低不就高原则降一下也没什么问题

**Comment by Coooookies** [comment]
> 主要是 Win 7 / 8 常见 4.5 ~ 4.5.2 ，而且目前用到的这些接口没有看到高版本 .NET framework 的需求，按照就低不就高原则降一下也没什么问题

如果是兼容Win7/8的话就没有必要了，拳头那边疑似要更新客户端CEF版本，下个赛季大版本可能将无法使用Win7/8/8.1进行游戏
![1af3527d4e37720810a6cee93bea7fb](https://github.com/LeagueTavern/fix-lcu-window/assets/44562331/a507da97-ebcc-4595-bf3b-f948fae98902)
截图是来自朋友的

**Comment by Coooookies** [comment]
目前确实是发现了一名Win7用户存在兼容性问题的，但我打算用WinUI3做托盘控制了，所以大概率是这里降然后另外开个仓库写了

**Comment by mzji** [comment]
> 目前确实是发现了一名Win7用户存在兼容性问题的，但我打算用WinUI3做托盘控制了，所以大概率是这里降然后另外开个仓库写了

直接 WinForm 就行了吧，弄个托盘用不到 WinUI3 这种新玩意啊

**Comment by Coooookies** [comment]
> > 目前确实是发现了一名Win7用户存在兼容性问题的，但我打算用WinUI3做托盘控制了，所以大概率是这里降然后另外开个仓库写了
> 
> 直接 WinForm 就行了吧，弄个托盘用不到 WinUI3 这种新玩意啊

 主要是好看，我主业并不是开发而是设计，比较喜欢好看一点的东西

**Comment by mzji** [comment]
> > > 目前确实是发现了一名Win7用户存在兼容性问题的，但我打算用WinUI3做托盘控制了，所以大概率是这里降然后另外开个仓库写了
> > 
> > 
> > 直接 WinForm 就行了吧，弄个托盘用不到 WinUI3 这种新玩意啊
> 
> 主要是好看，我主业并不是开发而是设计，比较喜欢好看一点的东西

哈哈原来如此，了解了 👍
